# Generated by Django 5.2.1 on 2025-06-11 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_envios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='viaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_envios.viaje'),
        ),
    ]
