# Generated by Django 5.2.1 on 2025-06-11 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_autenticacion', '0004_sucursal_conductor_sucursal'),
        ('app_envios', '0003_alter_sucursal_latitud_alter_sucursal_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_origen', to='app_autenticacion.sucursal'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_autenticacion.sucursal'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_destino', to='app_autenticacion.sucursal'),
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
