# Generated by Django 5.2 on 2025-06-11 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_autenticacion', '0004_sucursal_conductor_sucursal'),
        ('app_envios', '0004_alter_paquete_destino_alter_viaje_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquete', to='app_autenticacion.sucursal'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='estado_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_envios.estadoentrega'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_origen', to='app_autenticacion.sucursal'),
        ),
    ]
