# Generated by Django 5.2.1 on 2025-06-11 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_autenticacion', '0004_sucursal_conductor_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_autenticacion.sucursal'),
        ),
    ]
